'use strict';


module.exports = {
  // Permission levels
  LOGIN_EDIT: { key: 'LOGIN_EDIT' },
  LOGIN_VIEW: { key: 'LOGIN_VIEW' },
  USER_DETAILS_EDIT: { key: 'USER_DETAILS_EDIT'},
  USER_BRIEF_VIEW: { key: 'USER_BRIEF_VIEW' },
  USER_DETAILS_VIEW: { key: 'USER_DETAILS_VIEW' },
  ACKNOWLEDGE_DETAILS_VIEW: { key: 'ACKNOWLEDGE_DETAILS_VIEW' },
  ACKNOWLEDGE_BRIEF_VIEW_PRIVATE: { key: 'ACKNOWLEDGE_BRIEF_VIEW_PRIVATE' },
  ACKNOWLEDGE_BRIEF_VIEW_PUBLIC: { key: 'ACKNOWLEDGE_BRIEF_VIEW_PUBLIC' },
  ACKNOWLEDGE_CREATE: { key: 'ACKNOWLEDGE_CREATE' },
};
