'use strict';


module.exports = {
  // Permission levels
  ACCOUNT_EDIT: { key: 'ACCOUNT_EDIT' },
  ACCOUNT_VIEW: { key: 'ACCOUNT_VIEW' },
  ACCOUNT_CREATE: { key: 'ACCOUNT_CREATE' },
  USER_DETAILS_EDIT: { key: 'USER_DETAILS_EDIT'},
  USER_BRIEF_VIEW: { key: 'USER_BRIEF_VIEW' },
  USER_DETAILS_VIEW: { key: 'USER_DETAILS_VIEW' },
  ACKNOWLEDGEMENT_DETAILS_VIEW: { key: 'ACKNOWLEDGEMENT_DETAILS_VIEW' },
  ACKNOWLEDGEMENT_BRIEF_VIEW_PRIVATE: { key: 'ACKNOWLEDGEMENT_BRIEF_VIEW_PRIVATE' },
  ACKNOWLEDGEMENT_BRIEF_VIEW_PUBLIC: { key: 'ACKNOWLEDGEMENT_BRIEF_VIEW_PUBLIC' },
  ACKNOWLEDGEMENT_CREATE: { key: 'ACKNOWLEDGEMENT_CREATE' },
};
