'use strict';


module.exports = {
  // Permission levels
  USER_DETAILS_EDIT: { key: 'USER_DETAILS_EDIT'},
  LOGIN_CHANGE: { key: 'LOGIN_CHANGE' },
  USER_BRIEF_VIEW: { key: 'USER_BRIEF_VIEW' },
  USER_DETAILS_VIEW: { key: 'USER_DETAILS_VIEW' },
  AWARD_DETAILS_VIEW: { key: 'AWARD_DETAILS_VIEW' },
  AWARD_BRIEF_VIEW_PRIVATE: { key: 'AWARD_BRIEF_VIEW_PRIVATE' },
  AWARD_BRIEF_VIEW_PUBLIC: { key: 'AWARD_BRIEF_VIEW_PUBLIC' },
  AWARD_CREATE: { key: 'AWARD_CREATE' },
};
